apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  labels:
    app: nginx-svc
    app.kubernetes.io/managed-by: grad-deploy
spec:
  type: ClusterIP
  selector:
    app: nginx-svc
  ports:
    - port: 80
      targetPort: 80